vhdl-sources += ez_usb_fx2.pkg.vhd
vhdl-sources += fx2_controller.vhd
vhdl-sources += fx2_to_axi4_stream.vhd
vhdl-sources += axi4_stream_to_fx2.vhd
deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_logic.bool
